name: projet_mobile
description: A Flutter authentication UI without backend integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.9.0
  google_ml_kit: ^0.20.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  audioplayers: ^6.4.0
  uuid: ^4.5.1
  http: ^1.4.0
  image: ^4.5.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
